title: OffSec Wiki
description: Sticky notes for pentesting. Search hacking techniques and tools for penetration testings, RedTeaming, bug bounty, CTFs. 
author: Muhammad
github:
  name: GitHub
  url: https://github.com/muhammd/
twitter:
  name: Twitter
  url: https://twitter.com/muhammdhaidari
hash_cracker:
  name: PenTest Tools
  url: https://PenTest.Tools/
